import type { INodeProperties } from 'n8n-workflow';

const listOperations = [
	'listAlertResults', 'listAuditLogCoverage', 'listCveManagement', 'listDeletedSites',
	'listSensitiveInfoTypeRulePackage', 'listSpoVersionCleanup', 'listSharePointExternalUsers',
	'listSharePointSharing', 'listSiteLibraries', 'listSiteProperties', 'listSiteRecycleBin',
	'listCopilotSettings', 'listCopilotUsage', 'listAgent365Packages',
	'listAgent365PackageDetail', 'listShadowAi',
];

const payloadOperations = [
	'addIntunePolicyClone', 'execAddCippCveException', 'execRemoveCippCveException',
	'execBulkRemoveSharingLinks', 'execRemoveSpoExternalUser', 'execRemoveSharingLink',
	'execRemoveSiteUser', 'execRestoreDeletedSite', 'execRestoreRecycleBinItems',
	'execSetLibraryPermission', 'execSetSiteProperties', 'execGdapRepairRoleMappings',
	'execCopilotSettings', 'execShadowAiSanction', 'execSamCertificate',
	'execBackupReplicationConfig',
];

const tenantSelector: INodeProperties = {
	displayName: 'Tenant', name: 'tenantFilter', type: 'resourceLocator',
	default: { mode: 'list', value: '' }, required: true,
	description: 'Tenant to send as tenantFilter',
	displayOptions: { show: { resource: ['cippV106'], v106IncludeTenant: [true] } },
	modes: [
		{ displayName: 'From List', name: 'list', type: 'list', typeOptions: { searchListMethod: 'tenantSearch', searchable: true } },
		{ displayName: 'By Domain', name: 'domain', type: 'string', placeholder: 'e.g. contoso.onmicrosoft.com' },
	],
};

const operations: Array<[string, string, string]> = [
	['Add Intune Policy Clone', 'addIntunePolicyClone', 'Add Intune policy clone'],
	['Execute Add CVE Exception', 'execAddCippCveException', 'Add CVE exception'],
	['Execute Backup Replication Config', 'execBackupReplicationConfig', 'Configure backup replication'],
	['Execute Bulk Remove Sharing Links', 'execBulkRemoveSharingLinks', 'Remove sharing links in bulk'],
	['Execute Copilot Settings', 'execCopilotSettings', 'Set Copilot settings'],
	['Execute GDAP Repair Role Mappings', 'execGdapRepairRoleMappings', 'Repair GDAP role mappings'],
	['Execute Remove CVE Exception', 'execRemoveCippCveException', 'Remove CVE exception'],
	['Execute Remove SharePoint External User', 'execRemoveSpoExternalUser', 'Remove SharePoint external user'],
	['Execute Remove Sharing Link', 'execRemoveSharingLink', 'Remove sharing link'],
	['Execute Remove Site User', 'execRemoveSiteUser', 'Remove site user'],
	['Execute Restore Deleted Site', 'execRestoreDeletedSite', 'Restore deleted site'],
	['Execute Restore Recycle Bin Items', 'execRestoreRecycleBinItems', 'Restore recycle bin items'],
	['Execute SAM Certificate', 'execSamCertificate', 'Execute SAM certificate action'],
	['Execute Set Library Permission', 'execSetLibraryPermission', 'Set library permission'],
	['Execute Set Site Properties', 'execSetSiteProperties', 'Set site properties'],
	['Execute Shadow AI Sanction', 'execShadowAiSanction', 'Sanction Shadow AI application'],
	['List Active Alert Results', 'listAlertResults', 'List active alert results'],
	['List Agent 365 Package Detail', 'listAgent365PackageDetail', 'List Agent 365 package detail'],
	['List Agent 365 Packages', 'listAgent365Packages', 'List Agent 365 packages'],
	['List Audit Log Coverage', 'listAuditLogCoverage', 'List audit log coverage'],
	['List Copilot Settings', 'listCopilotSettings', 'List Copilot settings'],
	['List Copilot Usage', 'listCopilotUsage', 'List Copilot usage'],
	['List CVE Management', 'listCveManagement', 'List CVE management'],
	['List Deleted Sites', 'listDeletedSites', 'List deleted SharePoint sites'],
	['List Sensitive Info Type Rule Package', 'listSensitiveInfoTypeRulePackage', 'List sensitive info type rule package'],
	['List Shadow AI', 'listShadowAi', 'List Shadow AI'],
	['List SharePoint External Users', 'listSharePointExternalUsers', 'List SharePoint external users'],
	['List SharePoint Sharing', 'listSharePointSharing', 'List SharePoint sharing report'],
	['List SharePoint Version Cleanup', 'listSpoVersionCleanup', 'List SharePoint version cleanup'],
	['List Site Libraries', 'listSiteLibraries', 'List site libraries'],
	['List Site Properties', 'listSiteProperties', 'List site properties'],
	['List Site Recycle Bin', 'listSiteRecycleBin', 'List site recycle bin'],
];

export const v106Operations: INodeProperties[] = [{
	displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
	displayOptions: { show: { resource: ['cippV106'] } },
	options: operations.map(([name, value, action]) => ({ name, value, action })),
	default: '',
}];

export const v106Fields: INodeProperties[] = [
	{ displayName: 'Include Tenant', name: 'v106IncludeTenant', type: 'boolean', default: true,
		description: 'Whether to add tenantFilter to the request body/query', displayOptions: { show: { resource: ['cippV106'] } } },
	tenantSelector,
	{ displayName: 'Return All', name: 'returnAll', type: 'boolean', default: false,
		description: 'Whether to return all results or only up to a given limit', displayOptions: { show: { resource: ['cippV106'], operation: listOperations } } },
	{ displayName: 'Limit', name: 'limit', type: 'number', typeOptions: { minValue: 1, maxValue: 500 }, default: 50,
		description: 'Max number of results to return', displayOptions: { show: { resource: ['cippV106'], operation: listOperations, returnAll: [false] } } },
	{ displayName: 'Query Parameters', name: 'v106QueryJson', type: 'json', default: '{}',
		description: 'Additional query parameters as a JSON object', displayOptions: { show: { resource: ['cippV106'] } } },
	{ displayName: 'Advanced Body Overrides', name: 'v106BodyJson', type: 'json', default: '{}',
		description: 'Optional JSON fields to merge into the typed request. Use this for CIPP fields not exposed below.', displayOptions: { show: { resource: ['cippV106'], operation: payloadOperations } } },
	{ displayName: 'CVE ID', name: 'v106CveId', type: 'string', default: '', required: true,
		displayOptions: { show: { resource: ['cippV106'], operation: ['execAddCippCveException', 'execRemoveCippCveException'] } } },
	{ displayName: 'Exception Type', name: 'v106CveExceptionType', type: 'options', default: 'RiskAccepted', required: true,
		options: [{ name: 'Compensating Control', value: 'CompensatingControl' }, { name: 'False Positive', value: 'FalsePositive' }, { name: 'Planned Remediation', value: 'PlannedRemediation' }, { name: 'Risk Accepted', value: 'RiskAccepted' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execAddCippCveException'] } } },
	{ displayName: 'Apply To', name: 'v106CveApplyTo', type: 'options', default: 'CurrentTenant', required: true,
		options: [{ name: 'Current Tenant', value: 'CurrentTenant' }, { name: 'All Affected Tenants', value: 'AllAffected' }, { name: 'Global', value: 'Global' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execAddCippCveException'] } } },
	{ displayName: 'Justification', name: 'v106CveJustification', type: 'string', typeOptions: { rows: 3 }, default: '', required: true,
		displayOptions: { show: { resource: ['cippV106'], operation: ['execAddCippCveException'] } } },
	{ displayName: 'Expiry Date', name: 'v106CveExpiryDate', type: 'dateTime', default: '',
		displayOptions: { show: { resource: ['cippV106'], operation: ['execAddCippCveException'] } } },
	{ displayName: 'Remove Scope', name: 'v106CveRemoveScope', type: 'options', default: 'CurrentTenant',
		options: [{ name: 'Current Tenant', value: 'CurrentTenant' }, { name: 'All Affected Tenants', value: 'AllAffected' }, { name: 'Global', value: 'Global' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveCippCveException'] } } },
	{ displayName: 'Setting', name: 'v106CopilotSettingId', type: 'options', default: 'microsoft.copilot.copilotchatpinning', required: true,
		options: [{ name: 'Allow Copilot in Admin Centers', value: 'microsoft.copilot.allowinadmincenters' }, { name: 'Allow Web Search', value: 'microsoft.copilot.allowwebsearch' }, { name: 'Block Access to Open Files', value: 'microsoft.copilot.blockaccesstoopenfiles' }, { name: 'Copilot Chat Pinning', value: 'microsoft.copilot.copilotchatpinning' }, { name: 'Image Generation', value: 'microsoft.copilot.imagegeneration' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execCopilotSettings'] } } },
	{ displayName: 'Desired State', name: 'v106CopilotValue', type: 'options', default: 'clear', required: true,
		options: [{ name: 'Disabled', value: '0' }, { name: 'Enabled', value: '1' }, { name: 'Not Configured', value: 'clear' }], displayOptions: { show: { resource: ['cippV106'], operation: ['execCopilotSettings'] } } },
	{ displayName: 'Tools', name: 'v106ShadowAiTools', type: 'string', default: '', required: true,
		placeholder: 'e.g. ChatGPT, Claude', description: 'Comma-separated AI tool names', displayOptions: { show: { resource: ['cippV106'], operation: ['execShadowAiSanction'] } } },
	{ displayName: 'Action', name: 'v106ShadowAiAction', type: 'options', default: 'Sanction', options: [{ name: 'Sanction', value: 'Sanction' }, { name: 'Remove Sanction', value: 'Remove' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execShadowAiSanction'] } } },
	{ displayName: 'Site URL', name: 'v106SiteUrl', type: 'string', default: '', required: true, placeholder: 'https://contoso.sharepoint.com/sites/example',
		displayOptions: { show: { resource: ['cippV106'], operation: ['execBulkRemoveSharingLinks', 'execRestoreDeletedSite', 'execRestoreRecycleBinItems', 'execSetLibraryPermission', 'execSetSiteProperties'] } } },
	{ displayName: 'Scope', name: 'v106SharingScope', type: 'options', default: 'Anonymous', options: [{ name: 'Anonymous', value: 'Anonymous' }, { name: 'External', value: 'External' }, { name: 'All', value: 'All' }],
		displayOptions: { show: { resource: ['cippV106'], operation: ['execBulkRemoveSharingLinks'] } } },
	{ displayName: 'Drive ID', name: 'v106DriveId', type: 'string', default: '', required: true, displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSharingLink'] } } },
	{ displayName: 'Item ID', name: 'v106ItemId', type: 'string', default: '', required: true, displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSharingLink'] } } },
	{ displayName: 'Permission ID', name: 'v106PermissionId', type: 'string', default: '', required: true, displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSharingLink'] } } },
	{ displayName: 'Site URLs', name: 'v106SiteUrls', type: 'string', default: '', description: 'Comma-separated site URLs. Required for Remove Site User.', displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSpoExternalUser', 'execRemoveSiteUser'] } } },
	{ displayName: 'User Login Name', name: 'v106LoginName', type: 'string', default: '', description: 'User principal or SharePoint login name. Required for Remove Site User.', displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSpoExternalUser', 'execRemoveSiteUser'] } } },
	{ displayName: 'Entra User ID', name: 'v106EntraUserId', type: 'string', default: '', displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSpoExternalUser'] } } },
	{ displayName: 'Display Name', name: 'v106ExternalUserDisplayName', type: 'string', default: '', displayOptions: { show: { resource: ['cippV106'], operation: ['execRemoveSpoExternalUser'] } } },
	{ displayName: 'Recycle Bin Item IDs', name: 'v106RecycleBinItemIds', type: 'string', default: '', required: true, description: 'Comma-separated item IDs', displayOptions: { show: { resource: ['cippV106'], operation: ['execRestoreRecycleBinItems'] } } },
	{ displayName: 'Library ID', name: 'v106LibraryId', type: 'string', default: '', required: true, displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Library Name', name: 'v106LibraryName', type: 'string', default: '', required: true, displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Permission Level', name: 'v106LibraryPermissionLevel', type: 'options', default: 'read', options: [{ name: 'Contribute', value: 'contribute' }, { name: 'Design', value: 'design' }, { name: 'Edit', value: 'edit' }, { name: 'Full Control', value: 'fullControl' }, { name: 'Read', value: 'read' }], displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Users', name: 'v106LibraryUsers', type: 'string', default: '', description: 'Optional comma-separated user principal names', displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Security Groups', name: 'v106LibraryGroups', type: 'string', default: '', description: 'Optional comma-separated Microsoft Entra security group IDs', displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Microsoft 365 Groups', name: 'v106LibraryM365Groups', type: 'string', default: '', description: 'Optional comma-separated Microsoft 365 group IDs', displayOptions: { show: { resource: ['cippV106'], operation: ['execSetLibraryPermission'] } } },
	{ displayName: 'Site Properties', name: 'v106SiteProperties', type: 'collection', placeholder: 'Add Property', default: {},
		displayOptions: { show: { resource: ['cippV106'], operation: ['execSetSiteProperties'] } }, options: [
			{ displayName: 'Default Link Permission', name: 'DefaultLinkPermission', type: 'options', default: 'None', options: [{ name: 'Edit', value: 'Edit' }, { name: 'Tenant Default', value: 'None' }, { name: 'View', value: 'View' }] },
			{ displayName: 'Default Sharing Link Type', name: 'DefaultSharingLinkType', type: 'options', default: 'None', options: [{ name: 'Anyone', value: 'AnonymousAccess' }, { name: 'Internal', value: 'Internal' }, { name: 'Specific People', value: 'Direct' }, { name: 'Tenant Default', value: 'None' }] },
			{ displayName: 'Lock State', name: 'LockState', type: 'options', default: 'Unlock', options: [{ name: 'No Access', value: 'NoAccess' }, { name: 'Read Only', value: 'ReadOnly' }, { name: 'Unlocked', value: 'Unlock' }] },
			{ displayName: 'Sharing Capability', name: 'SharingCapability', type: 'options', default: 'Disabled', options: [{ name: 'Anyone', value: 'ExternalUserAndGuestSharing' }, { name: 'Disabled', value: 'Disabled' }, { name: 'Existing Guests Only', value: 'ExistingExternalUserSharingOnly' }, { name: 'New and Existing Guests', value: 'ExternalUserSharingOnly' }] },
			{ displayName: 'Site Name', name: 'Title', type: 'string', default: '' },
			{ displayName: 'Storage Maximum Level (MB)', name: 'StorageMaximumLevel', type: 'number', default: 0, typeOptions: { minValue: 0 } },
			{ displayName: 'Storage Warning Level (MB)', name: 'StorageWarningLevel', type: 'number', default: 0, typeOptions: { minValue: 0 } },
		] },
	{ displayName: 'Options', name: 'v106Options', type: 'collection', placeholder: 'Add Option', default: {},
		displayOptions: { show: { resource: ['cippV106'] } }, options: [{ displayName: 'Max Payload Bytes', name: 'maxPayloadBytes', type: 'number', typeOptions: { minValue: 1 }, default: 262144, description: 'Maximum serialized request body size' }] },
];
